package com.inn.cafe.dao;

import com.inn.cafe.POJO.User;
import com.inn.cafe.wrapper.UserWrapper;
import jakarta.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface UserDao extends JpaRepository<User, Integer> {

    User findByEmailId(@Param("email") String email);

    List<UserWrapper> getAllUser();
    List<String> getAllAdmins();

    @Transactional
    @Modifying //aplicar cuando se hacen operaciones de modificacion (update, delete)
    Integer updateStatus(@Param("status") String status, @Param("id") Integer id);

    User findByEmail(String email); //autogenerated query by JpaRepository
}
